version: "3.3"
services:
  db:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: snapp
      MYSQL_DATABASE: snapp
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
      - 3306:3306
#    expose:
#      - "3306"
  snapp:
    build: .
    network_mode: host
    restart: on-failure
    ports:
      - 8090:8090
    expose:
      - "8090"
    volumes:
      - "~/.m2/repository/:/root/.m2/repository/"
    depends_on:
      db:
        condition: service_healthy
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.177.57.0/24

