swagger: "2.0"
info:
  version: 0.0.0
  title: title
  description: description
  termsOfService: terms
  contact:
    name: "contact"
    url: http://localhost:8090
    email: saman.sarem@hotmail.com
  license:
    name: MIT
    url: http://localhost:8090
host: "localhost:8090"
paths:
  /contact:
    put:
      summary: "add contact"
      description: "add contact"
      operationId: "addNewContact"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Contact object that needs to be added to the database"
        required: true
        schema:
          $ref: '#/definitions/ContactDTO'
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: '#/definitions/ContactDTO'
    get:
      summary: "search contact"
      description: "search contact"
      operationId: "searchContact"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Contact example should be search in database"
        required: true
        schema:
          $ref: '#/definitions/ContactSearchDTO'
      responses:
        200:
          description: OK
    
definitions:
  ContactDTO:
    type: "object"
    properties:
      name:
        type: "string"
        example: "saman"
      phoneNumber:
        type: "string"
        example: "+989352490969"
      email:
        type: "string"
        example: "saman.sarem@hotmail.com"
      organization:
        type: "string"
        example: "snapp"
      github:
        type: "string"
        example: "https://github.com/cloudfoundry"
  ContactSearchDTO:
    type: "object"
    properties:
      name:
        type: "string"
        example: "saman"
      phoneNumber:
        type: "string"
        example: "+989352490969"
      email:
        type: "string"
        example: "saman.sarem@hotmail.com"
      organization:
        type: "string"
        example: "https://github.com/cloudfoundry"
