server:
  port: 8090
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/snapp?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: snapp
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect


